### PR TITLE
let `self` instead of let strongSelf in guard

### PR DESCRIPTION
**Pull request by konrado0905**

### CODE REVIEW

**Comment by rayfix** [comment]
`self` = self was originally considered but ruled out because it is (by some members of the core team) considered a bug.

**Comment by RobertGummesson** [comment]
Out of curiosity, why was it considered a bug?

**Comment by RobertGummesson** [comment]
Answering my own question. [It is a bug.](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160118/007425.html)

**Comment by yan-zaitsev** [comment]
@rayfix I checked Swift 4 code in playground and it is working perfectly. closure captures self as weak reference
```
class Test {
    public var call: (() -> ())? = nil
    public init() {
        self.call = { [weak self] in
            guard let `self` = self else { return print("No self") }
            print(String(describing: self))
        }
    }
}

var test: Test? = Test()
weak var test2 = test
var call = (test?.call)!

test?.call?() ?? print("No Test instance - it is wrong")
test = nil
call() ?? print("No Test instance - it is wrong")
test2?.call?() ?? print("No Test instance - it is OK")
```

**Comment by rafaelnobrepd** [comment]
Its a wonderful bug that should be integrated in the language

**Comment by k-marin** [comment]
it was never a bug, it was a mvp feature for the future :)
guard let self = self else { return } (Swift 4.2)

**Pull request closed without merging**
