### PR TITLE
Variable name for Optional Binding

### PR DESCRIPTION
**Pull request by gregheo**
To use the value of an optional property, we can use Optional Binding. For example:

``` swift
if let t = self.title {
  // do many things with title
}
```

But I'm always confused about the naming of the optionally bounded variable. In the case above, how should the variable `t` be named? Using the first letter is of course very bad! 

Any ideas?

### CODE REVIEW

**Comment by patchin** [comment]
:-1: I got here because I saw this shadowing being used in an NSHipster article w/o explanation and had to Google around to figure out what the real deal was. I won't be the only one. Feels hacky. Just to make it look nicer? Reminds me of the hubub concerning "optional" semicolons in javascript. Just because you can doesn't mean you should.

**Comment by johngoren** [comment]
I sometimes go with let title = myTitle, but this sounds like an online product name from 2002, so I change it to the more generous and plummy let title = ourTitle.

**Comment by ishuo** [comment]
@patchin  I am now used to the shadowing. Works pretty well in my projects, pragmatic! Of course you can make suggestions if you have better ideas.

**Comment by patchin** [comment]
How about: 
if let _foo = foo {
}
or:
if  _foo_ = foo {
}
It also has the visual effect of looking unwrapped.

**Comment by RobertGummesson** [comment]
Been following the various discussions on this topic and thought I'd add my view. To me, shadowing felt a bit strange at first just as not prefixing 'properties' with self did. Now I've gotten used to both and don't look back. 

I agree 100% with what @ColinEberhardt wrote on issue #75.
"Hungarian Notation has almost died out, there's no good reason to revive it!"

Regarding using underscores as prefixes, I don't personally distinguish between private and public variables in Swift. ...not yet. If I would, I imagine they would look like this:
private var _foo

I would in other words expect underscore to have the same meaning in Swift as in most other languages I've worked with. So I'd be careful giving them a different meaning in Swift.

**Comment by patchin** [comment]
1. In this case it's not a private variable (private class member as I think you're trying to say), it's a local variable.
2. Let's not call it Hungarian Notation because of all the bad connotations. I still think it's useful to be able to look at a line of code and divine what the types are without the assistance of the IDE. Especially when that code is published on a website, like GitHub.

**Comment by RobertGummesson** [comment]
@patchin - My point was that a local variable would then risk having the same prefix as a private class member. So far I haven't seen any guidelines for private vs. public class member prefixes but I would imagine that we'll get there one day even in Swift.

**Comment by patchin** [comment]
I swear, you've edited your comment after I've made mine. Ok then, use the underscore as a suffix.

**Pull request merged**
